# Generated by Django 5.2.5 on 2025-11-22 15:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('users', '0004_alter_student_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('school_start_time', models.TimeField(default='08:00')),
                ('school_end_time', models.TimeField(default='15:00')),
                ('late_arrival_threshold', models.PositiveSmallIntegerField(default=15, help_text='Minutes after start time considered as late')),
                ('min_attendance_percentage', models.DecimalField(decimal_places=2, default=75.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('half_day_threshold', models.PositiveSmallIntegerField(default=4, help_text='Hours required to count as full day')),
                ('auto_generate_reports', models.BooleanField(default=True, help_text='Automatically generate monthly reports')),
                ('report_generation_day', models.PositiveSmallIntegerField(default=1, help_text='Day of month to generate reports', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.section')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Configuration',
                'verbose_name_plural': 'Attendance Configurations',
                'db_table': 'attendance_configuration',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attendance_summary', serialize=False, to='users.student')),
                ('current_year', models.PositiveIntegerField()),
                ('total_days', models.PositiveSmallIntegerField(default=0)),
                ('days_present', models.PositiveSmallIntegerField(default=0)),
                ('days_absent', models.PositiveSmallIntegerField(default=0)),
                ('days_late', models.PositiveSmallIntegerField(default=0)),
                ('days_half_day', models.PositiveSmallIntegerField(default=0)),
                ('days_excused', models.PositiveSmallIntegerField(default=0)),
                ('overall_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current_streak', models.PositiveSmallIntegerField(default=0, help_text='Consecutive present days')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Summary',
                'verbose_name_plural': 'Attendance Summaries',
                'db_table': 'attendance_summary',
                'indexes': [models.Index(fields=['overall_percentage'], name='attendance__overall_17d244_idx'), models.Index(fields=['current_streak'], name='attendance__current_1072ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('excused', 'Excused'), ('holiday', 'Holiday'), ('sick_leave', 'Sick Leave')], db_index=True, max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to='users.teacher')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='users.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.subject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_attendances', to='users.teacher')),
            ],
            options={
                'verbose_name': 'Daily Attendance',
                'verbose_name_plural': 'Daily Attendances',
                'db_table': 'daily_attendance',
                'ordering': ['-date', 'student'],
                'indexes': [models.Index(fields=['student', 'date', 'subject'], name='daily_atten_student_7607c8_idx'), models.Index(fields=['section', 'date'], name='daily_atten_section_424486_idx'), models.Index(fields=['date', 'status'], name='daily_atten_date_8a0daf_idx')],
                'unique_together': {('student', 'date', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyAttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveIntegerField()),
                ('total_school_days', models.PositiveSmallIntegerField(default=0)),
                ('present_days', models.PositiveSmallIntegerField(default=0)),
                ('absent_days', models.PositiveSmallIntegerField(default=0)),
                ('late_days', models.PositiveSmallIntegerField(default=0)),
                ('half_days', models.PositiveSmallIntegerField(default=0)),
                ('excused_days', models.PositiveSmallIntegerField(default=0)),
                ('sick_leave_days', models.PositiveSmallIntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('punctuality_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('previous_month_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percentage_change', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='users.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Attendance Report',
                'verbose_name_plural': 'Monthly Attendance Reports',
                'db_table': 'monthly_attendance_reports',
                'ordering': ['-year', '-month', 'student'],
                'indexes': [models.Index(fields=['student', 'year', 'month'], name='monthly_att_student_c555e1_idx'), models.Index(fields=['attendance_percentage'], name='monthly_att_attenda_b3057c_idx'), models.Index(fields=['is_finalized'], name='monthly_att_is_fina_6e0296_idx')],
                'unique_together': {('student', 'month', 'year')},
            },
        ),
    ]
