# Generated by Django 5.2.5 on 2025-12-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('all', 'all'), ('students', 'students'), ('parents', 'parents'), ('teachers', 'teachers'), ('specific_class', 'specific_class')], max_length=20),
        ),
    ]
