# Generated by Django 5.2.5 on 2025-12-06 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('query_text', models.TextField()),
                ('response', models.TextField()),
                ('context', models.JSONField(default=dict)),
                ('hit_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rag_query_cache',
                'ordering': ['-hit_count'],
            },
        ),
        migrations.CreateModel(
            name='RAGMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('total_queries', models.IntegerField(default=0)),
                ('successful_queries', models.IntegerField(default=0)),
                ('failed_queries', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('cache_hit_rate', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'rag_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('context_used', models.JSONField(blank=True, default=list)),
                ('sql_queries', models.JSONField(blank=True, default=list)),
                ('tokens_used', models.IntegerField(default=0)),
                ('response_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rag_chat_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('txt', 'Text File'), ('csv', 'CSV File')], max_length=10)),
                ('file', models.FileField(upload_to='rag_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('vector_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rag_document_store',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
