# Generated by Django 5.2.5 on 2025-11-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_parent_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Employee', 'Employee'), ('student', 'student'), ('teacher', 'teacher'), ('parent', 'parent')], default='Customer', max_length=10),
        ),
    ]
