# Generated by Django 5.2.5 on 2025-11-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0002_alter_feeinvoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
