# Generated by Django 5.2.5 on 2025-11-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
