# Generated by Django 5.2.5 on 2025-12-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('cancelled', 'cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveapprovalworkflow',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('cancelled', 'cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leavehistory',
            name='new_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('cancelled', 'cancelled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leavehistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('cancelled', 'cancelled')], max_length=20, null=True),
        ),
    ]
