# Generated by Django 5.2.5 on 2026-01-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailtemplate',
            table='email_temp',
        ),
    ]
