# Generated by Django 5.2.5 on 2025-11-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0003_alter_feepayment_payment_id'),
        ('users', '0004_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feediscount',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Apply to all students if checked'),
        ),
        migrations.AddField(
            model_name='feediscount',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='fee_discounts', to='users.student'),
        ),
    ]
