from datetime import date, timedelta
from rest_framework import serializers
from django.core.validators import MinValueValidator, MaxValueValidator
from .models import Route, Vehicle, TransportAllocation
from apps.academic.serializers import AcademicYearListingSerializer
from apps.users.serializers import StudentListSerializer


# ==================== Route Serializers ====================

class RouteListingSerializer(serializers.ModelSerializer):
    """Minimal serializer for route listings"""
    
    class Meta:
        model = Route
        fields = ['id', 'name', 'code', 'start_point', 'end_point', 'distance', 'monthly_fee']


class RouteSerializer(serializers.ModelSerializer):
    """Full route serializer with validations"""
    created_by = serializers.SerializerMethodField()
    updated_by = serializers.SerializerMethodField()
    vehicles_count = serializers.SerializerMethodField()
    allocations_count = serializers.SerializerMethodField()
    
    class Meta:
        model = Route
        fields = [
            'id', 'name', 'code', 'start_point', 'end_point', 'distance',
            'monthly_fee', 'description',
            'vehicles_count', 'allocations_count',
            'created_by', 'updated_by', 'created_at', 'updated_at'
        ]
        read_only_fields = ('code', 'created_at', 'updated_at', 'created_by', 'updated_by')
    
    def get_created_by(self, obj):
        if obj.created_by:
            full_name = obj.created_by.get_full_name()
            return full_name.strip() if full_name and full_name.strip() else obj.created_by.username
        return None
    
    def get_updated_by(self, obj):
        if obj.updated_by:
            full_name = obj.updated_by.get_full_name()
            return full_name.strip() if full_name and full_name.strip() else obj.updated_by.username
        return None
    
    def get_vehicles_count(self, obj):
        if obj.deleted:
            return 0
        return obj.vehicle_set.filter(deleted=False).count()
    
    def get_allocations_count(self, obj):
        if obj.deleted:
            return 0
        return obj.transportallocation_set.filter(deleted=False, is_active=True).count()
    
    def validate_name(self, value):
        if len(value.strip()) < 2:
            raise serializers.ValidationError("Route name must be at least 2 characters long")
        
        qs = Route.objects.filter(name__iexact=value.strip(), deleted=False)
        # if self.instance:
        #     qs = qs.exclude(id=self.instance.id)
        
        # if qs.exists():
        #     raise serializers.ValidationError(f"Route with name '{value}' already exists")
        
        return value.strip()
    
    def validate_code(self, value):
        # Allow code to be empty for creation (will be auto-generated)
        if value and len(value.strip()) > 0:
            if len(value.strip()) < 2:
                raise serializers.ValidationError("Route code must be at least 2 characters long")
            
            qs = Route.objects.filter(code__iexact=value.strip(), deleted=False)
            if self.instance:
                qs = qs.exclude(id=self.instance.id)
            
            if qs.exists():
                raise serializers.ValidationError(f"Route with code '{value}' already exists")
            
            return value.strip().upper()
        return value  # Return as is if empty (will be auto-generated)
    
    def validate_start_point(self, value):
        if len(value.strip()) < 3:
            raise serializers.ValidationError("Start point must be at least 3 characters long")
        return value.strip()
    
    def validate_end_point(self, value):
        if len(value.strip()) < 3:
            raise serializers.ValidationError("End point must be at least 3 characters long")
        return value.strip()
    
    def validate_distance(self, value):
        if value <= 0:
            raise serializers.ValidationError("Distance must be greater than 0")
        if value > 999.99:
            raise serializers.ValidationError("Distance cannot exceed 999.99 KM")
        return value
    
    def validate_monthly_fee(self, value):
        if value <= 0:
            raise serializers.ValidationError("Monthly fee must be greater than 0")
        return value
    
    def create(self, validated_data):
        # Remove code from validated_data if empty or not provided
        code = validated_data.pop('code', None)
        if not code or len(code.strip()) == 0:
            # Code will be auto-generated by the model's save method
            pass
        else:
            validated_data['code'] = code
        
        # Create the instance
        instance = super().create(validated_data)
        return instance
    
    def update(self, instance, validated_data):
        # For updates, keep the existing code or use the provided one
        code = validated_data.get('code')
        if code and len(code.strip()) > 0:
            validated_data['code'] = code.strip().upper()
        
        return super().update(instance, validated_data)
    
    def to_representation(self, instance):
        if instance.deleted:
            return {
                'id': instance.id,
                'name': instance.name,
                'code': instance.code,
                'message': f'Route "{instance.name}" has been deleted successfully'
            }
        
        data = super().to_representation(instance)
        
        if isinstance(data.get('created_at'), str):
            data['created_at'] = data['created_at'].replace('T', ' ').split('.')[0]
        if isinstance(data.get('updated_at'), str):
            data['updated_at'] = data['updated_at'].replace('T', ' ').split('.')[0]
        
        return data

# ==================== Vehicle Serializers ====================

class VehicleListingSerializer(serializers.ModelSerializer):
    """Minimal serializer for vehicle listings"""
    route_name = serializers.CharField(source='route.name', read_only=True)
    
    class Meta:
        model = Vehicle
        fields = ['id', 'vehicle_number', 'vehicle_model', 'driver_name', 'route_name', 'is_active']


class VehicleSerializer(serializers.ModelSerializer):
    """Full vehicle serializer with validations"""
    created_by = serializers.SerializerMethodField()
    updated_by = serializers.SerializerMethodField()
    route_detail = serializers.SerializerMethodField()
    allocations_count = serializers.SerializerMethodField()
    insurance_status = serializers.SerializerMethodField()
    fitness_status = serializers.SerializerMethodField()
    
    class Meta:
        model = Vehicle
        fields = [
            'id', 'vehicle_number', 'vehicle_model', 'capacity',
            'driver_name', 'driver_phone', 'driver_license',
            'route', 'insurance_expiry', 'fitness_expiry', 'is_active',
            'route_detail', 'allocations_count', 'insurance_status', 'fitness_status',
            'created_by', 'updated_by', 'created_at', 'updated_at'
        ]
        read_only_fields = ('created_at', 'updated_at', 'created_by', 'updated_by')
    
    def get_created_by(self, obj):
        if obj.created_by:
            full_name = obj.created_by.get_full_name()
            return full_name.strip() if full_name and full_name.strip() else obj.created_by.username
        return None
    
    def get_updated_by(self, obj):
        if obj.updated_by:
            full_name = obj.updated_by.get_full_name()
            return full_name.strip() if full_name and full_name.strip() else obj.updated_by.username
        return None
    
    def get_route_detail(self, obj):
        if obj.route and not obj.route.deleted:
            return RouteListingSerializer(obj.route).data
        return None
    
    def get_allocations_count(self, obj):
        if obj.deleted:
            return 0
        return obj.transportallocation_set.filter(deleted=False, is_active=True).count()
    
    def get_insurance_status(self, obj):
        """Check if insurance is valid"""
        today = date.today()
        if obj.insurance_expiry < today:
            return 'expired'
        elif obj.insurance_expiry <= today + timedelta(days=30):
            return 'expiring_soon'
        return 'valid'
    
    def get_fitness_status(self, obj):
        """Check if fitness certificate is valid"""
        from datetime import timedelta
        today = date.today()
        if obj.fitness_expiry < today:
            return 'expired'
        elif obj.fitness_expiry <= today + timedelta(days=30):
            return 'expiring_soon'
        return 'valid'
    
    def validate_vehicle_number(self, value):
        if len(value.strip()) < 3:
            raise serializers.ValidationError("Vehicle number must be at least 3 characters long")
        
        qs = Vehicle.objects.filter(vehicle_number__iexact=value.strip(), deleted=False)
        if self.instance:
            qs = qs.exclude(id=self.instance.id)
        
        if qs.exists():
            raise serializers.ValidationError(f"Vehicle with number '{value}' already exists")
        
        return value.strip().upper()
    
    def validate_vehicle_model(self, value):
        if len(value.strip()) < 2:
            raise serializers.ValidationError("Vehicle model must be at least 2 characters long")
        return value.strip()
    
    def validate_capacity(self, value):
        if value <= 0:
            raise serializers.ValidationError("Capacity must be greater than 0")
        if value > 100:
            raise serializers.ValidationError("Capacity cannot exceed 100")
        return value
    
    def validate_driver_name(self, value):
        if len(value.strip()) < 2:
            raise serializers.ValidationError("Driver name must be at least 2 characters long")
        return value.strip()
    
    def validate_driver_phone(self, value):
        if len(value.strip()) < 10:
            raise serializers.ValidationError("Driver phone must be at least 10 characters long")
        return value.strip()
    
    def validate_driver_license(self, value):
        if len(value.strip()) < 5:
            raise serializers.ValidationError("Driver license must be at least 5 characters long")
        return value.strip().upper()
    
    def validate_route(self, value):
        if value and value.deleted:
            raise serializers.ValidationError("Cannot assign a deleted route")
        return value
    
    def validate_insurance_expiry(self, value):
        """Validate insurance expiry date"""
        if value < date.today():
            raise serializers.ValidationError("Insurance has already expired")
        return value
    
    def validate_fitness_expiry(self, value):
        """Validate fitness expiry date"""
        if value < date.today():
            raise serializers.ValidationError("Fitness certificate has already expired")
        return value
    
    def validate(self, data):
        """Cross-field validation"""
        insurance_expiry = data.get('insurance_expiry', getattr(self.instance, 'insurance_expiry', None))
        fitness_expiry = data.get('fitness_expiry', getattr(self.instance, 'fitness_expiry', None))
        
        # Check if vehicle can be marked active with expired documents
        is_active = data.get('is_active', getattr(self.instance, 'is_active', True))
        today = date.today()
        
        if is_active:
            if insurance_expiry and insurance_expiry < today:
                raise serializers.ValidationError({
                    'is_active': 'Cannot activate vehicle with expired insurance'
                })
            if fitness_expiry and fitness_expiry < today:
                raise serializers.ValidationError({
                    'is_active': 'Cannot activate vehicle with expired fitness certificate'
                })
        
        return data
    
    def to_representation(self, instance):
        if instance.deleted:
            return {
                'id': instance.id,
                'vehicle_number': instance.vehicle_number,
                'message': f'Vehicle "{instance.vehicle_number}" has been deleted successfully'
            }
        
        data = super().to_representation(instance)
        
        if isinstance(data.get('created_at'), str):
            data['created_at'] = data['created_at'].replace('T', ' ').split('.')[0]
        if isinstance(data.get('updated_at'), str):
            data['updated_at'] = data['updated_at'].replace('T', ' ').split('.')[0]
        
        return data


# ==================== Transport Allocation Serializers ====================

class TransportAllocationListingSerializer(serializers.ModelSerializer):
    """Minimal serializer for transport allocation listings"""
    student_name = serializers.SerializerMethodField()
    student_admission = serializers.SerializerMethodField()
    route_name = serializers.CharField(source='route.name', read_only=True)
    vehicle_number = serializers.CharField(source='vehicle.vehicle_number', read_only=True)
    
    class Meta:
        model = TransportAllocation
        fields = [
            'id', 'student_name', 'student_admission', 'route_name',
            'vehicle_number', 'pickup_point', 'is_active'
        ]
    
    def get_student_name(self, obj):
        if obj.student and obj.student.user:
            full_name = obj.student.user.get_full_name()
            return full_name.strip() if full_name and full_name.strip() else obj.student.user.username
        return None
    
    def get_student_admission(self, obj):
        if obj.student and hasattr(obj.student, 'admission_number'):
            return obj.student.admission_number
        return None


class TransportAllocationSerializer(serializers.ModelSerializer):
    """Full transport allocation serializer with validations"""
    created_by = serializers.SerializerMethodField()
    updated_by = serializers.SerializerMethodField()
    student_detail = serializers.SerializerMethodField()
    route_detail = serializers.SerializerMethodField()
    vehicle_detail = serializers.SerializerMethodField()
    academic_year_detail = serializers.SerializerMethodField()
    allocation_status = serializers.SerializerMethodField()
    
    class Meta:
        model = TransportAllocation
        fields = [
            'id', 'student', 'route', 'vehicle', 'pickup_point', 'drop_point',
            'academic_year', 'start_date', 'end_date', 'is_active',
            'student_detail', 'route_detail', 'vehicle_detail', 'academic_year_detail',
            'allocation_status',
            'created_by', 'updated_by', 'created_at', 'updated_at'
        ]
        read_only_fields = ('created_at', 'updated_at', 'created_by', 'updated_by')
    
    def get_created_by(self, obj):
        if obj.created_by:
            full_name = obj.created_by.get_full_name()
            return full_name.strip() if full_name and full_name.strip() else obj.created_by.username
        return None
    
    def get_updated_by(self, obj):
        if obj.updated_by:
            full_name = obj.updated_by.get_full_name()
            return full_name.strip() if full_name and full_name.strip() else obj.updated_by.username
        return None
    
    def get_student_detail(self, obj):
        if obj.student and not obj.student.deleted:
            return StudentListSerializer(obj.student).data
        return None
    
    def get_route_detail(self, obj):
        if obj.route and not obj.route.deleted:
            return RouteListingSerializer(obj.route).data
        return None
    
    def get_vehicle_detail(self, obj):
        if obj.vehicle and not obj.vehicle.deleted:
            return VehicleListingSerializer(obj.vehicle).data
        return None
    
    def get_academic_year_detail(self, obj):
        if obj.academic_year and not obj.academic_year.deleted:
            return AcademicYearListingSerializer(obj.academic_year).data
        return None
    
    def get_allocation_status(self, obj):
        """Get human-readable allocation status"""
        today = date.today()
        
        if not obj.is_active:
            return 'inactive'
        if obj.start_date > today:
            return 'scheduled'
        elif obj.end_date and obj.end_date < today:
            return 'expired'
        elif obj.start_date <= today and (not obj.end_date or obj.end_date >= today):
            return 'active'
        return 'unknown'
    
    def validate_student(self, value):
        if value.deleted:
            raise serializers.ValidationError("Cannot allocate transport to a deleted student")
        return value
    
    def validate_route(self, value):
        if value.deleted:
            raise serializers.ValidationError("Cannot use a deleted route")
        return value
    
    def validate_vehicle(self, value):
        if value and value.deleted:
            raise serializers.ValidationError("Cannot use a deleted vehicle")
        if value and not value.is_active:
            raise serializers.ValidationError("Cannot use an inactive vehicle")
        return value
    
    def validate_academic_year(self, value):
        if value.deleted:
            raise serializers.ValidationError("Cannot use a deleted academic year")
        return value
    
    def validate_pickup_point(self, value):
        if len(value.strip()) < 3:
            raise serializers.ValidationError("Pickup point must be at least 3 characters long")
        return value.strip()
    
    def validate_drop_point(self, value):
        if len(value.strip()) < 3:
            raise serializers.ValidationError("Drop point must be at least 3 characters long")
        return value.strip()
    
    def validate_start_date(self, value):
        """Validate start date"""
        if value < date.today():
            raise serializers.ValidationError("Start date cannot be in the past")
        return value
    
    def validate(self, data):
        """Cross-field validation"""
        start_date = data.get('start_date', getattr(self.instance, 'start_date', None))
        end_date = data.get('end_date', getattr(self.instance, 'end_date', None))
        student = data.get('student', getattr(self.instance, 'student', None))
        academic_year = data.get('academic_year', getattr(self.instance, 'academic_year', None))
        vehicle = data.get('vehicle', getattr(self.instance, 'vehicle', None))
        route = data.get('route', getattr(self.instance, 'route', None))
        
        # Validate end date is after start date
        if end_date and start_date and end_date < start_date:
            raise serializers.ValidationError({
                'end_date': 'End date must be after start date'
            })
        
        # Check for duplicate active allocation for student in same academic year
        if student and academic_year:
            qs = TransportAllocation.objects.filter(
                student=student,
                academic_year=academic_year,
                is_active=True,
                deleted=False
            )
            if self.instance:
                qs = qs.exclude(id=self.instance.id)
            
            if qs.exists():
                raise serializers.ValidationError(
                    f"Active transport allocation already exists for this student in {academic_year.name}"
                )
        
        # Validate vehicle belongs to the selected route
        if vehicle and route and vehicle.route_id != route.id:
            raise serializers.ValidationError({
                'vehicle': f'Vehicle "{vehicle.vehicle_number}" is not assigned to route "{route.name}"'
            })
        
        # Check vehicle capacity (optional, depends on business logic)
        if vehicle and vehicle.capacity:
            current_allocations = TransportAllocation.objects.filter(
                vehicle=vehicle,
                is_active=True,
                deleted=False
            )
            if self.instance:
                current_allocations = current_allocations.exclude(id=self.instance.id)
            
            if current_allocations.count() >= vehicle.capacity:
                raise serializers.ValidationError({
                    'vehicle': f'Vehicle "{vehicle.vehicle_number}" has reached its capacity of {vehicle.capacity}'
                })
        
        return data
    
    def to_representation(self, instance):
        if instance.deleted:
            student_identifier = "student"
            if instance.student:
                if hasattr(instance.student, 'admission_number') and instance.student.admission_number:
                    student_identifier = instance.student.admission_number
                elif instance.student.user:
                    full_name = instance.student.user.get_full_name()
                    student_identifier = full_name.strip() if full_name and full_name.strip() else instance.student.user.username
            
            return {
                'id': instance.id,
                'student': instance.student_id,
                'route': instance.route_id,
                'message': f'Transport allocation for {student_identifier} has been deleted successfully'
            }
        
        data = super().to_representation(instance)
        
        if isinstance(data.get('created_at'), str):
            data['created_at'] = data['created_at'].replace('T', ' ').split('.')[0]
        if isinstance(data.get('updated_at'), str):
            data['updated_at'] = data['updated_at'].replace('T', ' ').split('.')[0]
        
        return data