# Generated by Django 5.2.5 on 2025-12-03 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_student_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('application_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.IntegerField(editable=False)),
                ('reason', models.TextField()),
                ('attachment', models.FileField(blank=True, max_length=500, null=True, upload_to='leave_applications/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('cancelled', 'cancelled')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('address_during_leave', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leave_applications', to='users.teacher')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_leave_applications', to='users.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_leave_applications', to='users.teacher')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('academic_year', models.IntegerField(unique=True)),
                ('max_consecutive_days', models.IntegerField(default=30, help_text='Maximum consecutive leave days allowed')),
                ('advance_notice_days', models.IntegerField(default=7, help_text='Minimum advance notice required for leave application')),
                ('max_advance_days', models.IntegerField(default=90, help_text='Maximum days in advance leave can be applied')),
                ('require_multilevel_approval', models.BooleanField(default=False)),
                ('auto_approve_short_leaves', models.BooleanField(default=False, help_text='Auto-approve leaves shorter than specified days')),
                ('auto_approve_max_days', models.IntegerField(default=2, help_text='Maximum days for auto-approval')),
                ('allow_carry_over', models.BooleanField(default=True)),
                ('max_carry_over_days', models.IntegerField(default=10)),
                ('carry_over_validity_months', models.IntegerField(default=3, help_text='Months into next academic year when carried over leaves expire')),
                ('notify_applicant_on_status_change', models.BooleanField(default=True)),
                ('notify_reviewer_on_new_application', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one configuration can be active at a time')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Leave Configurations',
                'db_table': 'leave_configurations',
            },
        ),
        migrations.CreateModel(
            name='LeaveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('modified', 'Modified'), ('forwarded', 'Forwarded'), ('withdrawn', 'Withdrawn')], max_length=50)),
                ('previous_status', models.CharField(blank=True, choices=[('pending', 'pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('cancelled', 'cancelled')], max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, choices=[('pending', 'pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('cancelled', 'cancelled')], max_length=20, null=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON representation of changed fields')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('leave_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='leave.leaveapplication')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Leave Histories',
                'db_table': 'leave_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('max_days_per_year', models.IntegerField(default=30)),
                ('requires_approval', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='leave.leavetype'),
        ),
        migrations.CreateModel(
            name='LeaveApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('approval_level', models.IntegerField(choices=[(1, 'Level 1 - Immediate Supervisor'), (2, 'Level 2 - Department Head'), (3, 'Level 3 - HR/Administration'), (4, 'Level 4 - Principal/Director')])),
                ('status', models.CharField(choices=[('pending', 'pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('cancelled', 'cancelled')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, help_text='Deadline for approval at this level', null=True)),
                ('is_current_level', models.BooleanField(default=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvals', to='users.teacher')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('leave_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflow', to='leave.leaveapplication')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_approval_workflows',
                'ordering': ['approval_level'],
                'unique_together': {('leave_application', 'approval_level')},
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('academic_year', models.IntegerField()),
                ('total_allocated', models.IntegerField(default=0)),
                ('used', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0, editable=False)),
                ('carried_over', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='users.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='users.teacher')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leave.leavetype')),
            ],
            options={
                'verbose_name_plural': 'Leave Balances',
                'db_table': 'leave_balances',
                'unique_together': {('student', 'leave_type', 'academic_year'), ('teacher', 'leave_type', 'academic_year')},
            },
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['status'], name='leave_appli_status_bbe471_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['start_date', 'end_date'], name='leave_appli_start_d_424510_idx'),
        ),
    ]
