# Generated by Django 5.2.5 on 2025-12-04 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leaveapplication_status_and_more'),
        ('users', '0004_alter_student_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['teacher'], name='leave_appli_teacher_9720ab_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['student'], name='leave_appli_student_4c80e1_idx'),
        ),
    ]
