# Generated by Django 5.2.5 on 2025-12-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leaveapplication_leave_appli_teacher_9720ab_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='code',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
