# Generated by Django 5.2.5 on 2025-11-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('dropout', 'Dropout'), ('transferred', 'Transferred'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
