# Generated by Django 5.2.5 on 2026-01-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_employee_options_remove_teacher_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permission',
            table='permissions',
        ),
    ]
