# Generated by Django 5.2.5 on 2026-01-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_permission_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employees',
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='usertoken',
            table='usertoken',
        ),
    ]
